language: php

sudo: false

php:
  - 7.1
  - 7.0

install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit tests/JsonValidatorTest