language: php

sudo: false

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4

install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit tests/JsonValidatorTest